name: blog
description: daniel neves
meta_description: "meu laboratório de ideias e pensamentos"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: "http://danielneves.com/blog"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
# url: ""
# author: Daniel Neves"

# Disqus config
disqus-shortname: ""
